import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Bar from '@/components/Bar/Bar';
import ClientSessionProvider from '@/components/ClientSessionProvider/ClientSessionProvider';
import { StoreProvider } from '@/store/StoreProvider';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientSessionProvider>
          <StoreProvider>
            <AntdRegistry>
              <Bar />
              {children}
            </AntdRegistry>
          </StoreProvider>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
